### ISSUE TITLE
Comment

### ISSUE THREAD

**Issue by Firtzberg** [fisharebest/flysystem-chroot-adapter#1]
Thank you for sharing your code!
I think it would be better to have a AdapterInterface as argument in ChrootAdapter constructor.

**Comment by fisharebest** [comment]
Hi @Firtzberg,

I made this change in v1.0.1 - or have I misunderstood you?

**Comment by Firtzberg** [comment]
The commit for v1.0.1 is good. You switched from a class to an interface.

What I am talking about is that you pass an FilesystemInterface in the constructor and only use it's adapter (didn't check all the code). Consider instead passing the AdapterInterface directly.

**Comment by fisharebest** [comment]
My use-case for this project was

(a) my application has a `Filesystem` instance to store its data.  It is is provided by a framework.
(b) I need to use libraries that also require their own flysystem-based storage

This module allows the application to hand off a sub-folder to the library.  It can be certain that the library cannot affect anything outside its own sub-folder.

Using an adapter wouldn't work for me.  My application doesn't have an adapter - it only has a filesystem.


Looking again at the 1.0.1 change, I think it might have been a mistake...

The function `::getAdapter()` does NOT exist in the interface - it only exists in the concrete class.

**Comment by Firtzberg** [comment]
Maybe you can do both.
Have an adapter that 'subfolders' an existing adapter and a filesystem that 'subfolders' an existing filesystem.
I think interfaces are a step forward.
